server:
  port: 19097
spring:
  application:
    name: notice-service
  datasource:
    url: jdbc:postgresql://localhost:5432/b2b
    username: postgres
    password: s5554549
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  slack:
    request-url: ${SLACK_REQUEST_URL}